info:
  contact: {}
paths:
  /books:
    get:
      consumes:
      - application/json
      description: return all Books
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - books
    post:
      consumes:
      - application/json
      description: register new book
      produces:
      - application/json
      responses:
        "201":
          description: Created
      tags:
      - books
  /books/:id:
    get:
      consumes:
      - application/json
      description: return specific book
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      tags:
      - books
  /checkout:
    patch:
      consumes:
      - application/json
      description: rent a specific book
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - checkout
  /return:
    patch:
      consumes:
      - application/json
      description: return a specific book
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - return
swagger: "2.0"
